#RedstoneNet Global Cloud Settings
#Sun Apr 05 12:22:11 CEST 2026
motd.enabled=true
motd.line1=&3&lRedstoneNet &8| &bCloudSystem
motd.line2=&7We are &aONLINE&7\! Come and play with us.
motd.maintenance.line1=&3&lRedstoneNet &8| &bCloudSystem &c[Maintenance]
motd.maintenance.line2=&cMaintenance &8| &7We'll be back soon\!
motd.player.info=&e%online% Players
msg.fallbackKick=&cDu wurdest auf die Lobby gesendet\: &7%reason%
msg.maintenanceKick=&cThe network is currently in maintenance mode\!\n&7Please come back later.
nametags.enabled=true
sign.line1.offline=&b[Cloud]
sign.line1.online=&b[Cloud]
sign.line2.offline=&7%server%
sign.line2.online=&7%server%
sign.line3.offline=&cOffline
sign.line3.online=&aOnline
sign.line4.offline=&8-
sign.line4.online=&8%online% Players
tablist.enabled=true
tablist.footer=&7Shop\: &bshop.redstone.net\n&e%online% &7Players online
tablist.header=&3&lRedstoneNet &8- &bCloud\n&7You are playing on\: &e%server%
